# Generated by Django 4.0.6 on 2022-07-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Login',
        ),
    ]
