# Generated by Django 4.0.6 on 2022-07-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crops',
        ),
    ]
