# Generated by Django 4.0.6 on 2022-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soil', '0004_delete_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.IntegerField()),
                ('Phosphorous', models.IntegerField()),
                ('Potassium', models.IntegerField()),
                ('Temperature', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('pH_Level', models.IntegerField()),
                ('Rainfall', models.IntegerField()),
                ('Crop_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Crops',
            },
        ),
    ]
