# Generated by Django 4.0.6 on 2022-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilisers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.IntegerField()),
                ('Phosphorous', models.IntegerField()),
                ('Potassium', models.IntegerField()),
                ('pH_Level', models.IntegerField()),
                ('Soil_Moisture', models.IntegerField()),
                ('Crop_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Fertilisers',
            },
        ),
    ]
